const path = require("path");

module.exports = {
  darkMode: "class",
  content: [
    path.resolve(__dirname, "./packages/**/src/**/*.{stories}.{tsx,ts,js}"),
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: [
          "ui-serif",
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "Times",
          "serif",
        ],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      colors: {
        inherit: "var(--color-inherit)",
        transparent: "var(--color-transparent)",
        black: "var(--color-black)",
        white: "var(--color-white)",
        gray: {
          50: "var(--color-gray-50)",
          100: "var(--color-gray-100)",
          200: "var(--color-gray-200)",
          300: "var(--color-gray-300)",
          400: "var(--color-gray-400)",
          500: "var(--color-gray-500)",
          600: "var(--color-gray-600)",
          700: "var(--color-gray-700)",
          800: "var(--color-gray-800)",
          900: "var(--color-gray-900)",
        },
        blue: {
          50: "var(--color-blue-50)",
          100: "var(--color-blue-100)",
          200: "var(--color-blue-200)",
          300: "var(--color-blue-300)",
          400: "var(--color-blue-400)",
          500: "var(--color-blue-500)",
          600: "var(--color-blue-600)",
          700: "var(--color-blue-700)",
          800: "var(--color-blue-800)",
          900: "var(--color-blue-900)",
        },
        green: {
          50: "var(--color-green-50)",
          100: "var(--color-green-100)",
          200: "var(--color-green-200)",
          300: "var(--color-green-300)",
          400: "var(--color-green-400)",
          500: "var(--color-green-500)",
          600: "var(--color-green-600)",
          700: "var(--color-green-700)",
          800: "var(--color-green-800)",
          900: "var(--color-green-900)",
        },
        red: {
          50: "var(--color-red-50)",
          100: "var(--color-red-100)",
          200: "var(--color-red-200)",
          300: "var(--color-red-300)",
          400: "var(--color-red-400)",
          500: "var(--color-red-500)",
          600: "var(--color-red-600)",
          700: "var(--color-red-700)",
          800: "var(--color-red-800)",
          900: "var(--color-red-900)",
        },
        orange: {
          50: "var(--color-orange-50)",
          100: "var(--color-orange-100)",
          200: "var(--color-orange-200)",
          300: "var(--color-orange-300)",
          400: "var(--color-orange-400)",
          500: "var(--color-orange-500)",
          600: "var(--color-orange-600)",
          700: "var(--color-orange-700)",
          800: "var(--color-orange-800)",
          900: "var(--color-orange-900)",
        },
        yellow: {
          50: "var(--color-yellow-50)",
          100: "var(--color-yellow-100)",
          200: "var(--color-yellow-200)",
          300: "var(--color-yellow-300)",
          400: "var(--color-yellow-400)",
          500: "var(--color-yellow-500)",
          600: "var(--color-yellow-600)",
          700: "var(--color-yellow-700)",
          800: "var(--color-yellow-800)",
          900: "var(--color-yellow-900)",
        },
        teal: {
          50: "var(--color-teal-50)",
          100: "var(--color-teal-100)",
          200: "var(--color-teal-200)",
          300: "var(--color-teal-300)",
          400: "var(--color-teal-400)",
          500: "var(--color-teal-500)",
          600: "var(--color-teal-600)",
          700: "var(--color-teal-700)",
          800: "var(--color-teal-800)",
          900: "var(--color-teal-900)",
        },
        violet: {
          50: "var(--color-violet-50)",
          100: "var(--color-violet-100)",
          200: "var(--color-violet-200)",
          300: "var(--color-violet-300)",
          400: "var(--color-violet-400)",
          500: "var(--color-violet-500)",
          600: "var(--color-violet-600)",
          700: "var(--color-violet-700)",
          800: "var(--color-violet-800)",
          900: "var(--color-violet-900)",
        },
        cyan: {
          50: "var(--color-cyan-50)",
          100: "var(--color-cyan-100)",
          200: "var(--color-cyan-200)",
          300: "var(--color-cyan-300)",
          400: "var(--color-cyan-400)",
          500: "var(--color-cyan-500)",
          600: "var(--color-cyan-600)",
          700: "var(--color-cyan-700)",
          800: "var(--color-cyan-800)",
          900: "var(--color-cyan-900)",
        },
        amber: {
          50: "var(--color-amber-50)",
          100: "var(--color-amber-100)",
          200: "var(--color-amber-200)",
          300: "var(--color-amber-300)",
          400: "var(--color-amber-400)",
          500: "var(--color-amber-500)",
          600: "var(--color-amber-600)",
          700: "var(--color-amber-700)",
          800: "var(--color-amber-800)",
          900: "var(--color-amber-900)",
        },
        pink: {
          50: "var(--color-pink-50)",
          100: "var(--color-pink-100)",
          200: "var(--color-pink-200)",
          300: "var(--color-pink-300)",
          400: "var(--color-pink-400)",
          500: "var(--color-pink-500)",
          600: "var(--color-pink-600)",
          700: "var(--color-pink-700)",
          800: "var(--color-pink-800)",
          900: "var(--color-pink-900)",
        },
        purple: {
          50: "var(--color-purple-50)",
          100: "var(--color-purple-100)",
          200: "var(--color-purple-200)",
          300: "var(--color-purple-300)",
          400: "var(--color-purple-400)",
          500: "var(--color-purple-500)",
          600: "var(--color-purple-600)",
          700: "var(--color-purple-700)",
          800: "var(--color-purple-800)",
          900: "var(--color-purple-900)",
        },
        "white-overlay": {
          50: "var(--color-white-overlay-50)",
          100: "var(--color-white-overlay-100)",
          200: "var(--color-white-overlay-200)",
          300: "var(--color-white-overlay-300)",
          400: "var(--color-white-overlay-400)",
          500: "var(--color-white-overlay-500)",
          600: "var(--color-white-overlay-600)",
          700: "var(--color-white-overlay-700)",
          800: "var(--color-white-overlay-800)",
          900: "var(--color-white-overlay-900)",
        },
        "black-overlay": {
          50: "var(--color-black-overlay-50)",
          100: "var(--color-black-overlay-100)",
          200: "var(--color-black-overlay-200)",
          300: "var(--color-black-overlay-300)",
          400: "var(--color-black-overlay-400)",
          500: "var(--color-black-overlay-500)",
          600: "var(--color-black-overlay-600)",
          700: "var(--color-black-overlay-700)",
          800: "var(--color-black-overlay-800)",
          900: "var(--color-black-overlay-900)",
        },
        "dark-gray": {
          50: "var(--color-dark-gray-50)",
          100: "var(--color-dark-gray-100)",
          200: "var(--color-dark-gray-200)",
          250: "var(--color-dark-gray-250)",
          300: "var(--color-dark-gray-300)",
          400: "var(--color-dark-gray-400)",
          500: "var(--color-dark-gray-500)",
          600: "var(--color-dark-gray-600)",
          650: "var(--color-dark-gray-650)",
          700: "var(--color-dark-gray-700)",
          800: "var(--color-dark-gray-800)",
          900: "var(--color-dark-gray-900)",
        },
        "dark-blue": {
          50: "var(--color-dark-blue-50)",
          100: "var(--color-dark-blue-100)",
          200: "var(--color-dark-blue-200)",
          300: "var(--color-dark-blue-300)",
          400: "var(--color-dark-blue-400)",
          500: "var(--color-dark-blue-500)",
          600: "var(--color-dark-blue-600)",
          700: "var(--color-dark-blue-700)",
          800: "var(--color-dark-blue-800)",
          900: "var(--color-dark-blue-900)",
          "900-80": "var(--color-dark-blue-900-80)",
        },
        "dark-green": {
          50: "var(--color-dark-green-50)",
          100: "var(--color-dark-green-100)",
          200: "var(--color-dark-green-200)",
          300: "var(--color-dark-green-300)",
          400: "var(--color-dark-green-400)",
          500: "var(--color-dark-green-500)",
          600: "var(--color-dark-green-600)",
          700: "var(--color-dark-green-700)",
          800: "var(--color-dark-green-800)",
          900: "var(--color-dark-green-900)",
        },
        "dark-red": {
          50: "var(--color-dark-red-50)",
          100: "var(--color-dark-red-100)",
          200: "var(--color-dark-red-200)",
          300: "var(--color-dark-red-300)",
          400: "var(--color-dark-red-400)",
          500: "var(--color-dark-red-500)",
          600: "var(--color-dark-red-600)",
          700: "var(--color-dark-red-700)",
          800: "var(--color-dark-red-800)",
          900: "var(--color-dark-red-900)",
          "800-90": "var(--color-dark-red-800-90)",
          "900-90": "var(--color-dark-red-900-90)",
        },
        "dark-amber": {
          50: "var(--color-dark-amber-50)",
          100: "var(--color-dark-amber-100)",
          200: "var(--color-dark-amber-200)",
          300: "var(--color-dark-amber-300)",
          400: "var(--color-dark-amber-400)",
          500: "var(--color-dark-amber-500)",
          600: "var(--color-dark-amber-600)",
          700: "var(--color-dark-amber-700)",
          800: "var(--color-dark-amber-800)",
          900: "var(--color-dark-amber-900)",
        },
        "dark-orange": {
          50: "var(--color-dark-orange-50)",
          100: "var(--color-dark-orange-100)",
          200: "var(--color-dark-orange-200)",
          300: "var(--color-dark-orange-300)",
          400: "var(--color-dark-orange-400)",
          500: "var(--color-dark-orange-500)",
          600: "var(--color-dark-orange-600)",
          700: "var(--color-dark-orange-700)",
          800: "var(--color-dark-orange-800)",
          900: "var(--color-dark-orange-900)",
          "900-80": "var(--color-dark-orange-900-80)",
        },
        "dark-yellow": {
          50: "var(--color-dark-yellow-50)",
          100: "var(--color-dark-yellow-100)",
          200: "var(--color-dark-yellow-200)",
          300: "var(--color-dark-yellow-300)",
          400: "var(--color-dark-yellow-400)",
          500: "var(--color-dark-yellow-500)",
          600: "var(--color-dark-yellow-600)",
          700: "var(--color-dark-yellow-700)",
          800: "var(--color-dark-yellow-800)",
          900: "var(--color-dark-yellow-900)",
        },
        "dark-teal": {
          50: "var(--color-dark-teal-50)",
          100: "var(--color-dark-teal-100)",
          200: "var(--color-dark-teal-200)",
          300: "var(--color-dark-teal-300)",
          400: "var(--color-dark-teal-400)",
          500: "var(--color-dark-teal-500)",
          600: "var(--color-dark-teal-600)",
          700: "var(--color-dark-teal-700)",
          800: "var(--color-dark-teal-800)",
          900: "var(--color-dark-teal-900)",
        },
        "dark-cyan": {
          50: "var(--color-dark-cyan-50)",
          100: "var(--color-dark-cyan-100)",
          200: "var(--color-dark-cyan-200)",
          300: "var(--color-dark-cyan-300)",
          400: "var(--color-dark-cyan-400)",
          500: "var(--color-dark-cyan-500)",
          600: "var(--color-dark-cyan-600)",
          700: "var(--color-dark-cyan-700)",
          800: "var(--color-dark-cyan-800)",
          900: "var(--color-dark-cyan-900)",
        },
        "dark-purple": {
          50: "var(--color-dark-purple-50)",
          100: "var(--color-dark-purple-100)",
          200: "var(--color-dark-purple-200)",
          300: "var(--color-dark-purple-300)",
          400: "var(--color-dark-purple-400)",
          500: "var(--color-dark-purple-500)",
          600: "var(--color-dark-purple-600)",
          700: "var(--color-dark-purple-700)",
          800: "var(--color-dark-purple-800)",
          900: "var(--color-dark-purple-900)",
        },
        "dark-pink": {
          50: "var(--color-dark-pink-50)",
          100: "var(--color-dark-pink-100)",
          200: "var(--color-dark-pink-200)",
          300: "var(--color-dark-pink-300)",
          400: "var(--color-dark-pink-400)",
          500: "var(--color-dark-pink-500)",
          600: "var(--color-dark-pink-600)",
          700: "var(--color-dark-pink-700)",
          800: "var(--color-dark-pink-800)",
          900: "var(--color-dark-pink-900)",
          "900-80": "var(--color-dark-pink-900-80)",
        },
        "dark-violet": {
          50: "var(--color-dark-violet-50)",
          100: "var(--color-dark-violet-100)",
          200: "var(--color-dark-violet-200)",
          300: "var(--color-dark-violet-300)",
          400: "var(--color-dark-violet-400)",
          500: "var(--color-dark-violet-500)",
          600: "var(--color-dark-violet-600)",
          700: "var(--color-dark-violet-700)",
          800: "var(--color-dark-violet-800)",
          900: "var(--color-dark-violet-900)",
        },
        outline: {
          white: "var(--outline-white)",
          "gray-1": "var(--outline-gray-1)",
          "gray-2": "var(--outline-gray-2)",
          "gray-3": "var(--outline-gray-3)",
          "gray-4": "var(--outline-gray-4)",
          "gray-5": "var(--outline-gray-5)",
          "red-1": "var(--outline-red-1)",
          "red-2": "var(--outline-red-2)",
          "red-3": "var(--outline-red-3)",
          "green-1": "var(--outline-green-1)",
          "green-2": "var(--outline-green-2)",
          "amber-1": "var(--outline-amber-1)",
          "amber-2": "var(--outline-amber-2)",
          "blue-1": "var(--outline-blue-1)",
          "orange-1": "var(--outline-orange-1)",
          "gray-modals": "var(--outline-gray-modals)",
        },
        surface: {
          white: "var(--surface-white)",
          "gray-1": "var(--surface-gray-1)",
          "gray-2": "var(--surface-gray-2)",
          "gray-3": "var(--surface-gray-3)",
          "gray-4": "var(--surface-gray-4)",
          "gray-5": "var(--surface-gray-5)",
          "gray-6": "var(--surface-gray-6)",
          "gray-7": "var(--surface-gray-7)",
          "red-1": "var(--surface-red-1)",
          "red-2": "var(--surface-red-2)",
          "red-3": "var(--surface-red-3)",
          "red-4": "var(--surface-red-4)",
          "red-5": "var(--surface-red-5)",
          "red-6": "var(--surface-red-6)",
          "red-7": "var(--surface-red-7)",
          "green-1": "var(--surface-green-1)",
          "green-2": "var(--surface-green-2)",
          "green-3": "var(--surface-green-3)",
          "amber-1": "var(--surface-amber-1)",
          "amber-2": "var(--surface-amber-2)",
          "amber-3": "var(--surface-amber-3)",
          "blue-1": "var(--surface-blue-1)",
          "blue-2": "var(--surface-blue-2)",
          "blue-3": "var(--surface-blue-3)",
          "orange-1": "var(--surface-orange-1)",
          "cyan-1": "var(--surface-cyan-1)",
          "pink-1": "var(--surface-pink-1)",
          "menu-bar": "var(--surface-menu-bar)",
          "orange-2": "var(--surface-orange-2)",
          "violet-1": "var(--surface-violet-1)",
          "violet-2": "var(--surface-violet-2)",
          "purple-1": "var(--surface-purple-1)",
          "purple-2": "var(--surface-purple-2)",
          "yellow-1": "var(--surface-yellow-1)",
          "teal-1": "var(--surface-teal-1)",
          "teal-2": "var(--surface-teal-2)",
          "pink-2": "var(--surface-pink-2)",
          "cyan-2": "var(--surface-cyan-2)",
          cards: "var(--surface-cards)",
          modal: "var(--surface-modal)",
          selected: "var(--surface-selected)",
        },
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-default)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-default)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        none: "var(--shadow-none)",
      },
      container: {
        padding: {
          xl: "var(--container-padding-xl)",
        },
      },
      fontSize: {
        "2xs": [
          "var(--text-2xs-size)",
          {
            lineHeight: "var(--text-2xs-line-height)",
            letterSpacing: "var(--text-2xs-letter-spacing)",
            fontWeight: "var(--text-2xs-font-weight)",
          },
        ],
        xs: [
          "var(--text-xs-size)",
          {
            lineHeight: "var(--text-xs-line-height)",
            letterSpacing: "var(--text-xs-letter-spacing)",
            fontWeight: "var(--text-xs-font-weight)",
          },
        ],
        sm: [
          "var(--text-sm-size)",
          {
            lineHeight: "var(--text-sm-line-height)",
            letterSpacing: "var(--text-sm-letter-spacing)",
            fontWeight: "var(--text-sm-font-weight)",
          },
        ],
        base: [
          "var(--text-base-size)",
          {
            lineHeight: "var(--text-base-line-height)",
            letterSpacing: "var(--text-base-letter-spacing)",
            fontWeight: "var(--text-base-font-weight)",
          },
        ],
        lg: [
          "var(--text-lg-size)",
          {
            lineHeight: "var(--text-lg-line-height)",
            letterSpacing: "var(--text-lg-letter-spacing)",
            fontWeight: "var(--text-lg-font-weight)",
          },
        ],
        xl: [
          "var(--text-xl-size)",
          {
            lineHeight: "var(--text-xl-line-height)",
            letterSpacing: "var(--text-xl-letter-spacing)",
            fontWeight: "var(--text-xl-font-weight)",
          },
        ],
        "2xl": [
          "var(--text-2xl-size)",
          {
            lineHeight: "var(--text-2xl-line-height)",
            letterSpacing: "var(--text-2xl-letter-spacing)",
            fontWeight: "var(--text-2xl-font-weight)",
          },
        ],
        "3xl": [
          "var(--text-3xl-size)",
          {
            lineHeight: "var(--text-3xl-line-height)",
            fontWeight: "var(--text-3xl-font-weight)",
            letterSpacing: "var(--text-3xl-letter-spacing)",
          },
        ],
        "p-2xs": [
          "var(--text-p-2xs-size)",
          {
            lineHeight: "var(--text-p-2xs-line-height)",
            letterSpacing: "var(--text-p-2xs-letter-spacing)",
            fontWeight: "var(--text-p-2xs-font-weight)",
          },
        ],
        "p-xs": [
          "var(--text-p-xs-size)",
          {
            lineHeight: "var(--text-p-xs-line-height)",
            letterSpacing: "var(--text-p-xs-letter-spacing)",
            fontWeight: "var(--text-p-xs-font-weight)",
          },
        ],
        "p-sm": [
          "var(--text-p-sm-size)",
          {
            lineHeight: "var(--text-p-sm-line-height)",
            letterSpacing: "var(--text-p-sm-letter-spacing)",
            fontWeight: "var(--text-p-sm-font-weight)",
          },
        ],
        "p-base": [
          "var(--text-p-base-size)",
          {
            lineHeight: "var(--text-p-base-line-height)",
            letterSpacing: "var(--text-p-base-letter-spacing)",
            fontWeight: "var(--text-p-base-font-weight)",
          },
        ],
        "p-lg": [
          "var(--text-p-lg-size)",
          {
            lineHeight: "var(--text-p-lg-line-height)",
            letterSpacing: "var(--text-p-lg-letter-spacing)",
            fontWeight: "var(--text-p-lg-font-weight)",
          },
        ],
        "p-xl": [
          "var(--text-p-xl-size)",
          {
            lineHeight: "var(--text-p-xl-line-height)",
            letterSpacing: "var(--text-p-xl-letter-spacing)",
            fontWeight: "var(--text-p-xl-font-weight)",
          },
        ],
        "p-2xl": [
          "var(--text-p-2xl-size)",
          {
            lineHeight: "var(--text-p-2xl-line-height)",
            letterSpacing: "var(--text-p-2xl-letter-spacing)",
            fontWeight: "var(--text-p-2xl-font-weight)",
          },
        ],
        "p-3xl": [
          "var(--text-p-3xl-size)",
          {
            lineHeight: "var(--text-p-3xl-line-height)",
            fontWeight: "var(--text-p-3xl-font-weight)",
            letterSpacing: "var(--text-p-3xl-letter-spacing)",
          },
        ],
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
      },
      textColor: {
        ink: {
          white: "var(--ink-white)",
          "gray-1": "var(--ink-gray-1)",
          "gray-2": "var(--ink-gray-2)",
          "gray-3": "var(--ink-gray-3)",
          "gray-4": "var(--ink-gray-4)",
          "gray-5": "var(--ink-gray-5)",
          "gray-6": "var(--ink-gray-6)",
          "gray-7": "var(--ink-gray-7)",
          "gray-8": "var(--ink-gray-8)",
          "gray-9": "var(--ink-gray-9)",
          "red-1": "var(--ink-red-1)",
          "red-2": "var(--ink-red-2)",
          "red-3": "var(--ink-red-3)",
          "red-4": "var(--ink-red-4)",
          "green-1": "var(--ink-green-1)",
          "green-2": "var(--ink-green-2)",
          "green-3": "var(--ink-green-3)",
          "amber-1": "var(--ink-amber-1)",
          "amber-2": "var(--ink-amber-2)",
          "amber-3": "var(--ink-amber-3)",
          "blue-1": "var(--ink-blue-1)",
          "blue-2": "var(--ink-blue-2)",
          "blue-3": "var(--ink-blue-3)",
          "cyan-1": "var(--ink-cyan-1)",
          "pink-1": "var(--ink-pink-1)",
          "violet-1": "var(--ink-violet-1)",
          "blue-link": "var(--ink-blue-link)",
        },
      },
      backgroundColor: {
        surface: {
          white: "var(--surface-white)",
          "gray-1": "var(--surface-gray-1)",
          "gray-2": "var(--surface-gray-2)",
          "gray-3": "var(--surface-gray-3)",
          "gray-4": "var(--surface-gray-4)",
          "gray-5": "var(--surface-gray-5)",
          "gray-6": "var(--surface-gray-6)",
          "gray-7": "var(--surface-gray-7)",
          "red-1": "var(--surface-red-1)",
          "red-2": "var(--surface-red-2)",
          "red-3": "var(--surface-red-3)",
          "red-4": "var(--surface-red-4)",
          "red-5": "var(--surface-red-5)",
          "red-6": "var(--surface-red-6)",
          "red-7": "var(--surface-red-7)",
          "green-1": "var(--surface-green-1)",
          "green-2": "var(--surface-green-2)",
          "green-3": "var(--surface-green-3)",
          "amber-1": "var(--surface-amber-1)",
          "amber-2": "var(--surface-amber-2)",
          "amber-3": "var(--surface-amber-3)",
          "blue-1": "var(--surface-blue-1)",
          "blue-2": "var(--surface-blue-2)",
          "blue-3": "var(--surface-blue-3)",
          "orange-1": "var(--surface-orange-1)",
          "violet-1": "var(--surface-violet-1)",
          "cyan-1": "var(--surface-cyan-1)",
          "pink-1": "var(--surface-pink-1)",
          "menu-bar": "var(--surface-menu-bar)",
          cards: "var(--surface-cards)",
          modal: "var(--surface-modal)",
          selected: "var(--surface-selected)",
          "orange-2": "var(--surface-orange-2)",
          "violet-2": "var(--surface-violet-2)",
          "purple-1": "var(--surface-purple-1)",
          "purple-2": "var(--surface-purple-2)",
          "yellow-1": "var(--surface-yellow-1)",
          "teal-1": "var(--surface-teal-1)",
          "teal-2": "var(--surface-teal-2)",
          "pink-2": "var(--surface-pink-2)",
          "cyan-2": "var(--surface-cyan-2)",
        },
      },
      borderColor: {
        outline: {
          white: "var(--outline-white)",
          "gray-1": "var(--outline-gray-1)",
          "gray-2": "var(--outline-gray-2)",
          "gray-3": "var(--outline-gray-3)",
          "gray-4": "var(--outline-gray-4)",
          "gray-5": "var(--outline-gray-5)",
          "red-1": "var(--outline-red-1)",
          "red-2": "var(--outline-red-2)",
          "red-3": "var(--outline-red-3)",
          "green-1": "var(--outline-green-1)",
          "green-2": "var(--outline-green-2)",
          "amber-1": "var(--outline-amber-1)",
          "amber-2": "var(--outline-amber-2)",
          "blue-1": "var(--outline-blue-1)",
          "orange-1": "var(--outline-orange-1)",
          "gray-modals": "var(--outline-gray-modals)",
        },
      },
      fill: {
        ink: {
          white: "var(--ink-white)",
          "gray-1": "var(--ink-gray-1)",
          "gray-2": "var(--ink-gray-2)",
          "gray-3": "var(--ink-gray-3)",
          "gray-4": "var(--ink-gray-4)",
          "gray-5": "var(--ink-gray-5)",
          "gray-6": "var(--ink-gray-6)",
          "gray-7": "var(--ink-gray-7)",
          "gray-8": "var(--ink-gray-8)",
          "gray-9": "var(--ink-gray-9)",
          "red-1": "var(--ink-red-1)",
          "red-2": "var(--ink-red-2)",
          "red-3": "var(--ink-red-3)",
          "red-4": "var(--ink-red-4)",
          "green-1": "var(--ink-green-1)",
          "green-2": "var(--ink-green-2)",
          "green-3": "var(--ink-green-3)",
          "amber-1": "var(--ink-amber-1)",
          "amber-2": "var(--ink-amber-2)",
          "amber-3": "var(--ink-amber-3)",
          "blue-1": "var(--ink-blue-1)",
          "blue-2": "var(--ink-blue-2)",
          "blue-3": "var(--ink-blue-3)",
          "cyan-1": "var(--ink-cyan-1)",
          "pink-1": "var(--ink-pink-1)",
          "violet-1": "var(--ink-violet-1)",
          "blue-link": "var(--ink-blue-link)",
        },
        surface: {
          white: "var(--surface-white)",
          "gray-1": "var(--surface-gray-1)",
          "gray-2": "var(--surface-gray-2)",
          "gray-3": "var(--surface-gray-3)",
          "gray-4": "var(--surface-gray-4)",
          "gray-5": "var(--surface-gray-5)",
          "gray-6": "var(--surface-gray-6)",
          "gray-7": "var(--surface-gray-7)",
          "red-1": "var(--surface-red-1)",
          "red-2": "var(--surface-red-2)",
          "red-3": "var(--surface-red-3)",
          "red-4": "var(--surface-red-4)",
          "red-5": "var(--surface-red-5)",
          "red-6": "var(--surface-red-6)",
          "red-7": "var(--surface-red-7)",
          "green-1": "var(--surface-green-1)",
          "green-2": "var(--surface-green-2)",
          "green-3": "var(--surface-green-3)",
          "amber-1": "var(--surface-amber-1)",
          "amber-2": "var(--surface-amber-2)",
          "amber-3": "var(--surface-amber-3)",
          "blue-1": "var(--surface-blue-1)",
          "blue-2": "var(--surface-blue-2)",
          "blue-3": "var(--surface-blue-3)",
          "orange-1": "var(--surface-orange-1)",
          "violet-1": "var(--surface-violet-1)",
          "cyan-1": "var(--surface-cyan-1)",
          "pink-1": "var(--surface-pink-1)",
          "menu-bar": "var(--surface-menu-bar)",
          cards: "var(--surface-cards)",
          modal: "var(--surface-modal)",
          selected: "var(--surface-selected)",
          "orange-2": "var(--surface-orange-2)",
          "violet-2": "var(--surface-violet-2)",
          "purple-1": "var(--surface-purple-1)",
          "purple-2": "var(--surface-purple-2)",
          "yellow-1": "var(--surface-yellow-1)",
          "teal-1": "var(--surface-teal-1)",
          "teal-2": "var(--surface-teal-2)",
          "pink-2": "var(--surface-pink-2)",
          "cyan-2": "var(--surface-cyan-2)",
        },
      },
      stroke: {
        ink: {
          white: "var(--ink-white)",
          "gray-1": "var(--ink-gray-1)",
          "gray-2": "var(--ink-gray-2)",
          "gray-3": "var(--ink-gray-3)",
          "gray-4": "var(--ink-gray-4)",
          "gray-5": "var(--ink-gray-5)",
          "gray-6": "var(--ink-gray-6)",
          "gray-7": "var(--ink-gray-7)",
          "gray-8": "var(--ink-gray-8)",
          "gray-9": "var(--ink-gray-9)",
          "red-1": "var(--ink-red-1)",
          "red-2": "var(--ink-red-2)",
          "red-3": "var(--ink-red-3)",
          "red-4": "var(--ink-red-4)",
          "green-1": "var(--ink-green-1)",
          "green-2": "var(--ink-green-2)",
          "green-3": "var(--ink-green-3)",
          "amber-1": "var(--ink-amber-1)",
          "amber-2": "var(--ink-amber-2)",
          "amber-3": "var(--ink-amber-3)",
          "blue-1": "var(--ink-blue-1)",
          "blue-2": "var(--ink-blue-2)",
          "blue-3": "var(--ink-blue-3)",
          "cyan-1": "var(--ink-cyan-1)",
          "pink-1": "var(--ink-pink-1)",
          "violet-1": "var(--ink-violet-1)",
          "blue-link": "var(--ink-blue-link)",
        },
      },
      placeholderColor: {
        ink: {
          white: "var(--ink-white)",
          "gray-1": "var(--ink-gray-1)",
          "gray-2": "var(--ink-gray-2)",
          "gray-3": "var(--ink-gray-3)",
          "gray-4": "var(--ink-gray-4)",
          "gray-5": "var(--ink-gray-5)",
          "gray-6": "var(--ink-gray-6)",
          "gray-7": "var(--ink-gray-7)",
          "gray-8": "var(--ink-gray-8)",
          "gray-9": "var(--ink-gray-9)",
          "red-1": "var(--ink-red-1)",
          "red-2": "var(--ink-red-2)",
          "red-3": "var(--ink-red-3)",
          "red-4": "var(--ink-red-4)",
          "green-1": "var(--ink-green-1)",
          "green-2": "var(--ink-green-2)",
          "green-3": "var(--ink-green-3)",
          "amber-1": "var(--ink-amber-1)",
          "amber-2": "var(--ink-amber-2)",
          "amber-3": "var(--ink-amber-3)",
          "blue-1": "var(--ink-blue-1)",
          "blue-2": "var(--ink-blue-2)",
          "blue-3": "var(--ink-blue-3)",
          "cyan-1": "var(--ink-cyan-1)",
          "pink-1": "var(--ink-pink-1)",
          "violet-1": "var(--ink-violet-1)",
          "blue-link": "var(--ink-blue-link)",
        },
      },
      ringColor: {
        outline: {
          white: "var(--outline-white)",
          "gray-1": "var(--outline-gray-1)",
          "gray-2": "var(--outline-gray-2)",
          "gray-3": "var(--outline-gray-3)",
          "gray-4": "var(--outline-gray-4)",
          "gray-5": "var(--outline-gray-5)",
          "red-1": "var(--outline-red-1)",
          "red-2": "var(--outline-red-2)",
          "red-3": "var(--outline-red-3)",
          "green-1": "var(--outline-green-1)",
          "green-2": "var(--outline-green-2)",
          "amber-1": "var(--outline-amber-1)",
          "amber-2": "var(--outline-amber-2)",
          "blue-1": "var(--outline-blue-1)",
          "orange-1": "var(--outline-orange-1)",
          "gray-modals": "var(--outline-gray-modals)",
        },
      },
      divideColor: {
        outline: {
          white: "var(--outline-white)",
          "gray-1": "var(--outline-gray-1)",
          "gray-2": "var(--outline-gray-2)",
          "gray-3": "var(--outline-gray-3)",
          "gray-4": "var(--outline-gray-4)",
          "gray-5": "var(--outline-gray-5)",
          "red-1": "var(--outline-red-1)",
          "red-2": "var(--outline-red-2)",
          "red-3": "var(--outline-red-3)",
          "green-1": "var(--outline-green-1)",
          "green-2": "var(--outline-green-2)",
          "amber-1": "var(--outline-amber-1)",
          "amber-2": "var(--outline-amber-2)",
          "blue-1": "var(--outline-blue-1)",
          "orange-1": "var(--outline-orange-1)",
          "gray-modals": "var(--outline-gray-modals)",
        },
      },
      spacing: {
        13: "var(--spacing-13)",
        15: "var(--spacing-15)",
        4.5: "var(--spacing-4_5)",
        5.5: "var(--spacing-5_5)",
        6.5: "var(--spacing-6_5)",
        7.5: "var(--spacing-7_5)",
        8.5: "var(--spacing-8_5)",
        9.5: "var(--spacing-9_5)",
        10.5: "var(--spacing-10_5)",
        11.5: "var(--spacing-11_5)",
        12.5: "var(--spacing-12_5)",
        13.5: "var(--spacing-13_5)",
        14.5: "var(--spacing-14_5)",
        15.5: "var(--spacing-15_5)",
        112: "var(--spacing-112)",
      },
      width: {
        112: "var(--spacing-112)",
        3.5: "var(--width-3_5)",
        wizard: "var(--width-wizard)",
      },
      height: {
        3.5: "var(--height-3_5)",
      },
      minWidth: {
        40: "var(--min-width-40)",
        50: "var(--min-width-50)",
      },
      maxHeight: {
        52: "var(--max-height-52)",
      },
    },
  },
  plugins: [],
};
